<?php

namespace Dywee\ProductCMSBundle\Repository;

/**
 * LatestProductContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LatestProductContainerRepository extends \Doctrine\ORM\EntityRepository
{
}
