<?php

namespace Dywee\ProductCMSBundle\Repository;

/**
 * LatestProductElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductElementRepository extends \Doctrine\ORM\EntityRepository
{
}
