<?php

namespace Dywee\ProductCMSBundle\Repository;

/**
 * ProductReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
