<?php

namespace Dywee\ProductCMSBundle\Repository;

/**
 * ProductGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
