<?php

namespace Dywee\ProductCMSBundle\Repository;

/**
 * ProductContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductContainerRepository extends \Doctrine\ORM\EntityRepository
{
}
